//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package shadowmage.ancient_warfare.client.model;

import org.lwjgl.opengl.GL11;

import shadowmage.meim.common.util.Trig;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.common.ForgeDirection;
 
 
public class ModelEngineWheel extends ModelBase
{
 
ModelRenderer wheelAxle;
ModelRenderer spoke1;
ModelRenderer paddle1;
ModelRenderer spoke2;
ModelRenderer paddle2;
ModelRenderer paddle3;
ModelRenderer paddle4;
public ModelEngineWheel(){
  wheelAxle = new ModelRenderer(this,"wheelAxle");
  wheelAxle.setTextureOffset(7,0);
  wheelAxle.setTextureSize(96,96);
  wheelAxle.setRotationPoint(0.0f, 0.0f, 8.0f);
  setPieceRotation(wheelAxle,0.0f, 0.0f, 0.0f);
  wheelAxle.addBox(-0.5f,-0.5f,0.0f,1,1,8);
  spoke1 = new ModelRenderer(this,"spoke1");
  spoke1.setTextureOffset(0,0);
  spoke1.setTextureSize(96,96);
  spoke1.setRotationPoint(0.0f, 0.0f, 6.0f);
  setPieceRotation(spoke1,0.0f, 0.0f, 0.0f);
  spoke1.addBox(-1.0f,-21.5f,0.0f,2,42,1);
  wheelAxle.addChild(spoke1);
  paddle1 = new ModelRenderer(this,"paddle1");
  paddle1.setTextureOffset(7,10);
  paddle1.setTextureSize(96,96);
  paddle1.setRotationPoint(0.0f, 0.0f, 5.0f);
  setPieceRotation(paddle1,0.0f, 0.0f, 0.0f);
  paddle1.addBox(-0.5f,12.0f,-4.0f,1,10,12);
  wheelAxle.addChild(paddle1);
  spoke2 = new ModelRenderer(this,"spoke2");
  spoke2.setTextureOffset(0,0);
  spoke2.setTextureSize(96,96);
  spoke2.setRotationPoint(0.0f, 0.0f, 6.01f);
  setPieceRotation(spoke2,0.0f, 0.0f, 1.5707964f);
  spoke2.addBox(-1.0f,-21.5f,0.0f,2,42,1);
  wheelAxle.addChild(spoke2);
  paddle2 = new ModelRenderer(this,"paddle2");
  paddle2.setTextureOffset(7,10);
  paddle2.setTextureSize(96,96);
  paddle2.setRotationPoint(0.0f, 0.0f, 5.0f);
  setPieceRotation(paddle2,0.0f, 8.322378E-9f, -1.5707964f);
  paddle2.addBox(-0.5f,12.0f,-4.0f,1,10,12);
  wheelAxle.addChild(paddle2);
  paddle3 = new ModelRenderer(this,"paddle3");
  paddle3.setTextureOffset(7,10);
  paddle3.setTextureSize(96,96);
  paddle3.setRotationPoint(0.0f, 0.0f, 5.0f);
  setPieceRotation(paddle3,0.0f, 8.322378E-9f, -3.1415927f);
  paddle3.addBox(-0.5f,12.0f,-4.0f,1,10,12);
  wheelAxle.addChild(paddle3);
  paddle4 = new ModelRenderer(this,"paddle4");
  paddle4.setTextureOffset(7,10);
  paddle4.setTextureSize(96,96);
  paddle4.setRotationPoint(0.0f, 0.0f, 5.0f);
  setPieceRotation(paddle4,0.0f, 8.322378E-9f, 1.5707964f);
  paddle4.addBox(-0.5f,12.0f,-4.0f,1,10,12);
  wheelAxle.addChild(paddle4);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  wheelAxle.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }

public void setDirection(ForgeDirection d)
  {
  float x = 0;
  float y = 0;
  float z = 0;
  switch(d)
  {
  case DOWN:
  GL11.glRotatef(-90, 1, 0, 0);
  break;
  
  case UP:
  GL11.glRotatef(90, 1, 0, 0);
  break;
  
  case NORTH:
  break;
  
  case SOUTH: 
  GL11.glRotatef(180, 0, 1, 0);
  break;
  
  case EAST:
  GL11.glRotatef(-90, 0, 1, 0);
  break;
  
  case WEST:
  GL11.glRotatef(90, 0, 1, 0);
  break;
  
  }
  }

public void renderModel()
  {
  wheelAxle.render(0.0625f);
  }

public void setWheelRotation(float rot, float f)
  {
  wheelAxle.rotateAngleZ = Trig.toRadians(rot - f);
  }

}
