//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package shadowmage.ancient_warfare.client.model.redstone;

import shadowmage.ancient_warfare.common.machine.redstone.logic.IRedstoneLogicTile;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
 
 
public class ModelTileTest extends ModelBase
{
 
ModelRenderer part1;
public ModelTileTest(){
  part1 = new ModelRenderer(this,"part1");
  part1.setTextureOffset(0,0);
  part1.setTextureSize(256,256);
  part1.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(part1,0.0f, 0.0f, 0.0f);
  part1.addBox(-7.0f,8.0f,-7.0f,14,1,14);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  part1.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }

/**
 * 
 * @param partialTick
 */
public void render(IRedstoneLogicTile tile, float partialTick)
  {
  part1.render(0.0625f);
  }


}
