//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package foo.bad.pkg.set.yours.here;
 
 
public class ModelShot extends ModelBase
{
 
ModelRendererCustom Shape1;
ModelRendererCustom Shape5;
ModelRendererCustom Shape4;
ModelRendererCustom Shape3;
ModelRendererCustom Shape7;
ModelRendererCustom Shape2;
ModelRendererCustom Shape6;
ModelRendererCustom Shape11;
ModelRendererCustom Shape8;
ModelRendererCustom Shape10;
ModelRendererCustom Shape12;
ModelRendererCustom Shape9;
public ModelShot(){
  Shape1 = new ModelRendererCustom(this,"Shape1");
  Shape1.setTextureOffset(0,28);
  Shape1.setTextureSize(256,256);
  Shape1.setRotationPoint(-6.0f, 6.0f, -6.0f);
  setPieceRotation(Shape1,0.0f, 0.0f, 0.0f);
  Shape1.addBox(0.0f,0.0f,0.0f,12,1,12);
  Shape5 = new ModelRendererCustom(this,"Shape5");
  Shape5.setTextureOffset(27,71);
  Shape5.setTextureSize(256,256);
  Shape5.setRotationPoint(12.0f, -12.0f, 0.0f);
  setPieceRotation(Shape5,0.0f, 0.0f, 0.0f);
  Shape5.addBox(0.0f,0.0f,0.0f,1,12,12);
  Shape1.addChild(Shape5);
  Shape4 = new ModelRendererCustom(this,"Shape4");
  Shape4.setTextureOffset(27,45);
  Shape4.setTextureSize(256,256);
  Shape4.setRotationPoint(0.0f, -12.0f, -1.0f);
  setPieceRotation(Shape4,0.0f, 0.0f, 0.0f);
  Shape4.addBox(0.0f,0.0f,0.0f,12,12,1);
  Shape1.addChild(Shape4);
  Shape3 = new ModelRendererCustom(this,"Shape3");
  Shape3.setTextureOffset(49,28);
  Shape3.setTextureSize(256,256);
  Shape3.setRotationPoint(0.0f, -13.0f, 0.0f);
  setPieceRotation(Shape3,0.0f, 0.0f, 0.0f);
  Shape3.addBox(0.0f,0.0f,0.0f,12,1,12);
  Shape1.addChild(Shape3);
  Shape7 = new ModelRendererCustom(this,"Shape7");
  Shape7.setTextureOffset(0,71);
  Shape7.setTextureSize(256,256);
  Shape7.setRotationPoint(-1.0f, -12.0f, 0.0f);
  setPieceRotation(Shape7,0.0f, 0.0f, 0.0f);
  Shape7.addBox(0.0f,0.0f,0.0f,1,12,12);
  Shape1.addChild(Shape7);
  Shape2 = new ModelRendererCustom(this,"Shape2");
  Shape2.setTextureOffset(41,59);
  Shape2.setTextureSize(256,256);
  Shape2.setRotationPoint(1.0f, -14.0f, 1.0f);
  setPieceRotation(Shape2,0.0f, 0.0f, 0.0f);
  Shape2.addBox(0.0f,0.0f,0.0f,10,1,10);
  Shape1.addChild(Shape2);
  Shape6 = new ModelRendererCustom(this,"Shape6");
  Shape6.setTextureOffset(0,59);
  Shape6.setTextureSize(256,256);
  Shape6.setRotationPoint(1.0f, 1.0f, 1.0f);
  setPieceRotation(Shape6,0.0f, 0.0f, 0.0f);
  Shape6.addBox(0.0f,0.0f,0.0f,10,1,10);
  Shape1.addChild(Shape6);
  Shape11 = new ModelRendererCustom(this,"Shape11");
  Shape11.setTextureOffset(23,96);
  Shape11.setTextureSize(256,256);
  Shape11.setRotationPoint(-2.0f, -11.0f, 1.0f);
  setPieceRotation(Shape11,0.0f, 0.0f, 0.0f);
  Shape11.addBox(0.0f,0.0f,0.0f,1,10,10);
  Shape1.addChild(Shape11);
  Shape8 = new ModelRendererCustom(this,"Shape8");
  Shape8.setTextureOffset(0,45);
  Shape8.setTextureSize(256,256);
  Shape8.setRotationPoint(0.0f, -12.0f, 12.0f);
  setPieceRotation(Shape8,0.0f, 0.0f, 0.0f);
  Shape8.addBox(0.0f,0.0f,0.0f,12,12,1);
  Shape1.addChild(Shape8);
  Shape10 = new ModelRendererCustom(this,"Shape10");
  Shape10.setTextureOffset(0,16);
  Shape10.setTextureSize(256,256);
  Shape10.setRotationPoint(1.0f, -11.0f, 13.0f);
  setPieceRotation(Shape10,0.0f, 0.0f, 0.0f);
  Shape10.addBox(0.0f,0.0f,0.0f,10,10,1);
  Shape1.addChild(Shape10);
  Shape12 = new ModelRendererCustom(this,"Shape12");
  Shape12.setTextureOffset(0,96);
  Shape12.setTextureSize(256,256);
  Shape12.setRotationPoint(13.0f, -11.0f, 1.0f);
  setPieceRotation(Shape12,0.0f, 0.0f, 0.0f);
  Shape12.addBox(0.0f,0.0f,0.0f,1,10,10);
  Shape1.addChild(Shape12);
  Shape9 = new ModelRendererCustom(this,"Shape9");
  Shape9.setTextureOffset(23,16);
  Shape9.setTextureSize(256,256);
  Shape9.setRotationPoint(1.0f, -11.0f, -2.0f);
  setPieceRotation(Shape9,0.0f, 0.0f, 0.0f);
  Shape9.addBox(0.0f,0.0f,0.0f,10,10,1);
  Shape1.addChild(Shape9);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  Shape1.bindParentTexture(entity.getTexture());
  Shape1.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }
}
