//auto-generated model template
//template generated by MEIM
//template v 1.0
//author Shadowmage45 (shadowage_catapults@hotmail.com)
 
package foo.bad.pkg.set.yours.here;
 
 
public class ModelTileLogicBase extends ModelTileLogicBase
{
 
ModelRenderer tileBase;
public ModelTileLogicBase(){
  tileBase = new ModelRenderer(this,"tileBase");
  tileBase.setTextureOffset(0,0);
  tileBase.setTextureSize(64,64);
  tileBase.setRotationPoint(0.0f, 0.0f, 0.0f);
  setPieceRotation(tileBase,0.0f, 0.0f, 0.0f);
  tileBase.addBox(-6.0f,7.99f,-6.0f,12,1,12);
  }
 
@Override
public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6)
  {
  super.render(entity, f1, f2, f3, f4, f5, f6);
  setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
  tileBase.render(f6);
  }
 
public void setPieceRotation(ModelRenderer model, float x, float y, float z)
  {
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
  }
}
